### ISSUE TITLE
fl.peaks~ crashing on Max 8, Win10

### ISSUE THREAD

**Issue by jessephamel** [AlexHarker/FrameLib#107]
Using fl.peaks~ seemingly in any context, including the help patch, immediately crashes Max.

Using 1.0.1 from package manager, Windows 10

**Comment by AlexHarker** [comment]
The bugs are not in fact related. This is fixed in 0aca2ecdf5248186a6a65b92b06e4a3be685df7e.

@jessephamel - sorry this took so long - you can check it out here:

https://github.com/AlexHarker/FrameLib/releases/tag/framelib-latest-main-2023-06-23

It would be great if you could confirm this works at your end.

**Comment by jessephamel** [comment]
> The bugs are not in fact related. This is fixed in [0aca2ec](https://github.com/AlexHarker/FrameLib/commit/0aca2ecdf5248186a6a65b92b06e4a3be685df7e).
> 
> @jessephamel - sorry this took so long - you can check it out here:
> 
> https://github.com/AlexHarker/FrameLib/releases/tag/framelib-latest-main-2023-06-23
> 
> It would be great if you could confirm this works at your end.

It seems to generally work, though the spectral example in the help patch still crashes

**Comment by AlexHarker** [comment]
Ah thanks @jessephamel - then there is still some kind of problem - what do you need to do to crash the spectral example - just switch on the DAC or are there specific settings?

**Comment by AlexHarker** [comment]
How about this one?

https://github.com/AlexHarker/FrameLib/releases/tag/framelib-latest-main-2023-06-30

@jessephamel

**Comment by jessephamel** [comment]
> How about this one?
> 
> https://github.com/AlexHarker/FrameLib/releases/tag/framelib-latest-main-2023-06-30
> 
> @jessephamel

Will have to play around some more, but the examples look good now!

**Comment by AlexHarker** [comment]
Closing...
